# Generated by Django 4.2.7 on 2023-12-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_comparisonsallers_rejected_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonsallers',
            name='all_product',
            field=models.PositiveIntegerField(
                default=0, verbose_name='Все товары организации'),
        ),
    ]
