# Generated by Django 4.2.7 on 2023-11-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerproducts',
            name='category_id',
            field=models.CharField(blank=True, null=True,
                                   verbose_name='ID категории'),
        ),
    ]
