# Generated by Django 4.2.7 on 2023-11-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_ownerproducts_ean_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerproducts',
            name='article',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='ownerproducts',
            name='name_1c',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Наименование товара Просепт в 1С'),
        ),
    ]
