# Generated by Django 4.2.7 on 2023-11-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_ownerproducts_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerproducts',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
    ]
