# Generated by Django 4.2.7 on 2023-11-29 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_alter_dealersnames_options'),
        ('owner', '0005_ownerproducts_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('matched', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('dealer_product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                 to='dealers.dealersproducts', verbose_name='Товар дилепа')),
                ('owner_product', models.ForeignKey(
                 on_delete=django.db.models.deletion.CASCADE,
                 to='owner.ownerproducts', verbose_name='Товар '
                                                        'производителя')),
            ],
            options={
                'verbose_name': 'Сопоставление товаров',
                'verbose_name_plural': 'Сопоставления товаров',
            },
        ),
    ]
