# Generated by Django 4.2.7 on 2023-12-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_alter_ownerproducts_wb_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrelation',
            name='matched',
        ),
    ]
