# Generated by Django 4.2.7 on 2023-11-28 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealersNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254,
                 unique=True, verbose_name='Наименование Дилера')),
            ],
        ),
        migrations.CreateModel(
            name='DealersProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(
                    max_length=254, verbose_name='Ключ(id) товара дилера')),
                ('price', models.DecimalField(blank=True, decimal_places=2,
                 max_digits=10, null=True, verbose_name='Цена дилера')),
                ('product_url', models.URLField(max_length=254,
                 verbose_name='Ссылка на товар дилера')),
                ('product_name', models.CharField(max_length=254,
                 unique=True, verbose_name='Наименование товара дилера')),
                ('date', models.CharField(help_text='Format: YYYY-MM-DD',
                 max_length=10, verbose_name='date')),
                ('matched', models.BooleanField(
                    default=False, verbose_name='Согласованный')),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  # noqa
                 related_name='dealer', to='dealers.dealersnames', verbose_name='ID дилера')),  # noqa
            ],
            options={
                'verbose_name': 'Продукт дилера',
                'verbose_name_plural': 'Продукты дилеров',
            },
        ),
    ]
