# Generated by Django 4.2.7 on 2023-11-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealersnames',
            options={'verbose_name': 'Наименование дилера', 'verbose_name_plural': 'Перечень дилеров'},
        ),
    ]
