# Generated by Django 4.2.7 on 2023-11-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_dealersnames_dealer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealersnames',
            options={'ordering': ('dealer_id',), 'verbose_name': 'Наименование дилера', 'verbose_name_plural': 'Перечень дилеров'},
        ),
    ]
