# Generated by Django 4.2.7 on 2023-11-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_alter_dealersnames_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealersproducts',
            name='product_name',
            field=models.CharField(
                max_length=254, verbose_name='Наименование товара дилера'),
        ),
    ]
