# Generated by Django 4.2.7 on 2023-12-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_alter_dealersproducts_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealersproducts',
            name='real_date',
            field=models.DateField(auto_now=True),
        ),
    ]
