# Generated by Django 4.2.7 on 2023-12-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0006_dealersproducts_real_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealersproducts',
            name='postponed',
            field=models.BooleanField(default=False,
                                      verbose_name='Отложенный'),
        ),
    ]
