name: Tes Workflow
on:
  repository_dispatch:
    types: [pull_request_closed_develop]

jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Print project tree
        run: tree .
